version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.3
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: nock
    versions:
    - 13.0.6
    - 13.0.7
    - 13.0.9
  - dependency-name: qs
    versions:
    - 6.9.6
