env:
  node: true
  es6: true
  mocha: true

parserOptions:
  ecmaVersion: 9

extends:
  - eslint:recommended
  - prettier

plugins:
  - mocha
  - import

rules:
  strict: ['error', 'safe']
  prefer-const: 'error'
  no-var: 'error'

  # Disable a couple rules from eslint:recommended.
  no-unused-vars: ['error', { 'args': 'none' }]
  no-console: 'off'

  'mocha/handle-done-callback': 'error'
  'mocha/no-global-tests': 'error'
  'mocha/no-mocha-arrows': 'error'
  'mocha/no-exclusive-tests': 'error'

  'import/order': ['error', { 'newlines-between': 'never' }]
